ALTER TABLE "PricingPolicy"
ADD COLUMN "monthlyFee" DECIMAL(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN "daytimeBlockFee" DECIMAL(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN "eveningBlockFee" DECIMAL(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN "overnightFlatFee" DECIMAL(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN "blockDurationMinutes" INTEGER NOT NULL DEFAULT 120,
ADD COLUMN "gracePeriodMinutes" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN "daytimeStartMinutes" INTEGER NOT NULL DEFAULT 360,
ADD COLUMN "daytimeEndMinutes" INTEGER NOT NULL DEFAULT 1049,
ADD COLUMN "eveningStartMinutes" INTEGER NOT NULL DEFAULT 1080,
ADD COLUMN "eveningEndMinutes" INTEGER NOT NULL DEFAULT 1439,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
